workflows:
  ios-build:
    name: Build iOS App
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      vars:
        xcodebuild \
  -project $XCODE_PROJECT \
        XCODE_SCHEME: "Atlas"
        BUNDLE_ID: "com.seuapp.atlas"
      xcode: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Instalar Dependências
        script: |
          gem install cocoapods
          if [ -d "ios" ]; then cd ios && pod install --verbose && cd ..; fi

      - name: Criar Arquivo Archive
        script: |
          xcodebuild \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $HOME/build/Atlas.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Exportar IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $HOME/build/Atlas.xcarchive \
            -exportPath $HOME/build \
            -exportOptionsPlist codemagic_exportOptions.plist \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    artifacts:
      - build/*.ipa
